name: Construir App Oficial (Google Play AAB y APK)

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar repositorio
      uses: actions/checkout@v4

    - name: ⚙️ Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 📦 Instalar Motor Capacitor y Plugins Nativos
      run: |
        npm install --legacy-peer-deps
        npm install @capacitor/filesystem @capacitor/share --legacy-peer-deps

    - name: 🤖 Generar Proyecto Android
      run: |
        npx cap add android
        npx cap sync android

    - name: ⬆️ Actualizar SDKs de Android
      run: |
        sed -i 's/minSdkVersion = .*/minSdkVersion = 23/g' android/variables.gradle
        sed -i 's/compileSdkVersion = .*/compileSdkVersion = 34/g' android/variables.gradle
        sed -i 's/targetSdkVersion = .*/targetSdkVersion = 34/g' android/variables.gradle

    - name: 🆙 Actualizar Gradle para soportar Java 21
      run: |
        sed -i 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.7-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties

    - name: 🎨 Recortar e Inyectar Ícono Personalizado
      run: |
        npm install @capacitor/assets -D --legacy-peer-deps
        npx capacitor-assets generate --android

    - name: ☕ Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: 📷 Inyectar Permisos de Cámara
      run: |
        sed -i '/<uses-permission android:name="android.permission.INTERNET" \/>/a \    <uses-permission android:name="android.permission.CAMERA" \/>' android/app/src/main/AndroidManifest.xml

    - name: 🏗️ Compilar AAB (Tienda) y APK (Pruebas)
      run: |
        cd android
        chmod +x gradlew
        ./gradlew bundleRelease assembleDebug

    - name: 🔐 Firmar Archivo Oficial (AAB)
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "$KEYSTORE_BASE64" | tr -d '\n\r ' | base64 --decode > release.keystore
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore release.keystore -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD android/app/build/outputs/bundle/release/app-release.aab $KEY_ALIAS

    - name: 📤 Subir AAB Firmado (Para Google Play)
      uses: actions/upload-artifact@v4
      with:
        name: ControlAsistencia-GooglePlay-AAB
        path: android/app/build/outputs/bundle/release/app-release.aab

    - name: 📲 Subir APK de Prueba (Para instalar en tu celular)
      uses: actions/upload-artifact@v4
      with:
        name: ControlAsistencia-Celular-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk